# version: '3.8'
# networks:
#   omni-backend:
#     external: false
# services:
#   omni-backend:
#     container_name: omni-backend
#     image: git.navigolabs.com/mayank/omni-backend:latest
#     build: .
#     networks:
#       - omni-backend
#     restart: always
#     # restart: no
#     # entrypoint: "tail -f /dev/null"
#     environment:
#       # Port on which service runs
#       - PORT=3000
#       - TCP_PORT=65432
#       # Server Host
#       - SERVER_HOST=0.0.0.0
#       # Node running environment
#       - NODE_ENV=production
#       # Database connectivity url
#       - DB_HOST=omni-backend-db
#       - DB_PORT=5432
#       - DB_USERNAME=omni-backend-user
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_DBNAME=omni-backend
#       - CORS_ALLOWED_ORIGINS=https://omni.navigolabs.com,http://localhost:3000,http://localhost:3001
#     ports:
#       - '127.0.0.1:3031:3000'
#       - '65432:65432'
#     volumes:
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     depends_on:
#       - omni-backend-db

#   omni-backend-db:
#     image: postgres:16
#     container_name: omni-backend-db
#     restart: always
#     environment:
#       - POSTGRES_USER=omni-backend-user
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=omni-backend
#     networks:
#       - omni-backend
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
