import { MigrationInterface, QueryRunner } from "typeorm";

export class PacketsSizeIncreaseNullable1732601133115 implements MigrationInterface {
    name = 'PacketsSizeIncreaseNullable1732601133115'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "login_packet" DROP COLUMN "imei"`);
        await queryRunner.query(`ALTER TABLE "login_packet" ADD "imei" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "header" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "vendorId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "firmwareVersion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "imei"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "imei" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "batteryPercentage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "lowBatteryThresholdPercentage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "memoryPercentage1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "memoryPercentage2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "dataUpdateRateWhenIgnitionOn" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "dataUpdateRateWhenIgnitionOff" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "digitalInputStatus"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "digitalInputStatus" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "checksum" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "startCharacter" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "packetHeader" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "vendorId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "firmwareVersion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "packetType"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "packetType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "messageId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "packetStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "packetStatus" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "imei" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "vehicleRegNo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gpsFix" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "date" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "time"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "time" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "latitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "latitudeDir"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "latitudeDir" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "longitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "longitudeDir"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "longitudeDir" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "speed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "heading" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "noOfSatellites" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "altitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "pdop" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "hdop" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "networkOperatorName"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "networkOperatorName" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "ignitionStatus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mainPowerStatus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mainInputVoltage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "internalBatteryVoltage" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "emergencyStatus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "tamperAlert"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "tamperAlert" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrength" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mccServing" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mncServing" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacServing"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacServing" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdServing"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdServing" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr1stNeighbour" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr1stNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr1stNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr1stNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr1stNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr2ndNeighbour" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr2ndNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr2ndNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr2ndNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr2ndNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr3rdNeighbour" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr3rdNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr3rdNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr3rdNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr3rdNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr4thNeighbour" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr4thNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr4thNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr4thNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr4thNeighbour" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "digitalInputStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "digitalInputStatus" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "digitalOutputStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "digitalOutputStatus" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "frameNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "analogInput1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "analogInput2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "deltaDistance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "otaResponse" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "endCharacter"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "endCharacter" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "checksum" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "startCharacter"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "startCharacter" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "packetHeader" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "vendorId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "messageType"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "messageType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "deviceId" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "packetType"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "packetType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "date" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "gps"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "gps" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "latitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "latitudeDirection"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "latitudeDirection" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "longitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "longitudeDirection"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "longitudeDirection" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "altitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "speed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "distance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "provider" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "vehicleRegNo"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "vehicleRegNo" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "replyNumber"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "replyNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "checksum" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "crc"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "crc" character varying(50)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "crc"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "crc" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "checksum" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "replyNumber"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "replyNumber" character varying(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "vehicleRegNo"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "vehicleRegNo" character varying(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "provider" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "distance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "speed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "altitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "longitudeDirection"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "longitudeDirection" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "longitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "latitudeDirection"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "latitudeDirection" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "latitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "gps"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "gps" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "date" character varying(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "packetType"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "packetType" character varying(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "deviceId" character varying(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "messageType"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "messageType" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "vendorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ALTER COLUMN "packetHeader" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" DROP COLUMN "startCharacter"`);
        await queryRunner.query(`ALTER TABLE "emergency_packet" ADD "startCharacter" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "checksum" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "endCharacter"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "endCharacter" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "otaResponse" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "deltaDistance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "analogInput2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "analogInput1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "frameNumber" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "digitalOutputStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "digitalOutputStatus" character varying(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "digitalInputStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "digitalInputStatus" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr4thNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr4thNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr4thNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr4thNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr4thNeighbour" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr3rdNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr3rdNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr3rdNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr3rdNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr3rdNeighbour" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr2ndNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr2ndNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr2ndNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr2ndNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr2ndNeighbour" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdNmr1stNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdNmr1stNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacNmr1stNeighbour"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacNmr1stNeighbour" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrengthNmr1stNeighbour" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "cellIdServing"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "cellIdServing" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "lacServing"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "lacServing" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mncServing" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mccServing" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gsmSignalStrength" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "tamperAlert"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "tamperAlert" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "emergencyStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "internalBatteryVoltage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mainInputVoltage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "mainPowerStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "ignitionStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "networkOperatorName"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "networkOperatorName" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "hdop" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "pdop" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "altitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "noOfSatellites" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "heading" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "speed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "longitudeDir"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "longitudeDir" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "longitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "latitudeDir"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "latitudeDir" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "latitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "time"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "time" character varying(6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "date" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "gpsFix" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "vehicleRegNo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "imei" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "packetStatus"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "packetStatus" character varying(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "messageId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" DROP COLUMN "packetType"`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ADD "packetType" character varying(2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "firmwareVersion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "vendorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "packetHeader" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_packet" ALTER COLUMN "startCharacter" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "checksum" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "digitalInputStatus"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "digitalInputStatus" character varying(4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "dataUpdateRateWhenIgnitionOff" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "dataUpdateRateWhenIgnitionOn" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "memoryPercentage2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "memoryPercentage1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "lowBatteryThresholdPercentage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "batteryPercentage" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" DROP COLUMN "imei"`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ADD "imei" character varying(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "firmwareVersion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "vendorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_monitoring_packet" ALTER COLUMN "header" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "login_packet" DROP COLUMN "imei"`);
        await queryRunner.query(`ALTER TABLE "login_packet" ADD "imei" character varying(15)`);
    }

}
