import { MigrationInterface, QueryRunner } from "typeorm";

export class DAuthorRelations1733745440305 implements MigrationInterface {
    name = 'DAuthorRelations1733745440305'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle_ecu" DROP CONSTRAINT "FK_c1a17e66d1050ff898975645761"`);
        await queryRunner.query(`CREATE TABLE "negative_response_codes" ("id" SERIAL NOT NULL, "response_code" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e097655f8f8f89f1750b374582" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parameters" ("id" SERIAL NOT NULL, "name" character varying(255), "description" character varying(500), "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b03a26baa3161f87fa87588859" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pid" ("id" SERIAL NOT NULL, "pid_code" character varying(255), "long_name" character varying(255), "description" character varying(500), "short_name" character varying(255), "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "total_length" integer, "byte_position" integer, "length_bytes" integer, "bit_coded" boolean NOT NULL DEFAULT false, "resolution" double precision, "offset" double precision, "min" double precision, "max" double precision, "read" boolean NOT NULL DEFAULT false, "write" boolean NOT NULL DEFAULT false, "unit" character varying(50), CONSTRAINT "PK_a5d41ad8c45b092c093afb4a227" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" SERIAL NOT NULL, "name" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pid_dataset" ("id" SERIAL NOT NULL, "name" character varying(255), "description" character varying(500), "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_93cc7dbec49555c4f822c649bd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dtc_dataset" ("id" SERIAL NOT NULL, "name" character varying(255), "description" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bb8f744d495929b0b44fd32dca9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ecu_management" ("id" SERIAL NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "mac_id" character varying(255), "ecu_name" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "protocol" character varying(255), "dtc_dataset" character varying(255), "pid_dataset" character varying(255), "rx_header" character varying(255), "tx_header" character varying(255), "read_dtc_fc_index" character varying(255), "clear_dtc_fn_index" character varying(255), "read_data_fn_index" character varying(255), "write_data_fn_index" character varying(255), "seedkey_algo_fn_index" character varying(255), "ior_test_index" character varying(255), "vehicle_id" integer, CONSTRAINT "PK_d56a0899905c4b11d8fd7ae2444" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "firmware_management" ("id" SERIAL NOT NULL, "firmware_version" character varying(255), "file" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "uploaded_by" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "vehicle_id" integer, CONSTRAINT "PK_6f928aa7223a067fe597c78791d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ecu_attributes" ("id" SERIAL NOT NULL, "attributeName" character varying(255) NOT NULL, "attributeValue" character varying(255) NOT NULL, "status" boolean NOT NULL, "isActive" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8c8205994aee342ae515514749f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ecu_neg" ("neg_id" integer NOT NULL, "ecu_id" integer NOT NULL, CONSTRAINT "PK_937b3359daa711df90c963e5f1d" PRIMARY KEY ("neg_id", "ecu_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1bf81b53a0a643f536e66755b6" ON "ecu_neg" ("neg_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_48c783f58fdae9de1ff18e4b84" ON "ecu_neg" ("ecu_id") `);
        await queryRunner.query(`CREATE TABLE "parameter_pid" ("parameter_id" integer NOT NULL, "pid_id" integer NOT NULL, CONSTRAINT "PK_99201a3bad517024f475b010527" PRIMARY KEY ("parameter_id", "pid_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bd37757d1cd557bcbf985dd3e" ON "parameter_pid" ("parameter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3cc4d1b98879c5f935bbe5257" ON "parameter_pid" ("pid_id") `);
        await queryRunner.query(`CREATE TABLE "pid_dataset_pid" ("pid_id" integer NOT NULL, "pid_dataset_id" integer NOT NULL, CONSTRAINT "PK_7eb1c36002764844403e2d8eb8a" PRIMARY KEY ("pid_id", "pid_dataset_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9eff1d7cfde8b0520f7f386336" ON "pid_dataset_pid" ("pid_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_42e3cc1aecf0dd92ae884bb6e2" ON "pid_dataset_pid" ("pid_dataset_id") `);
        await queryRunner.query(`CREATE TABLE "message_type_pid_dataset" ("message_type_id" integer NOT NULL, "pid_dataset_id" integer NOT NULL, CONSTRAINT "PK_c0ffa939b9fcc95116a7145b0f5" PRIMARY KEY ("message_type_id", "pid_dataset_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03da0196097403a22e19ac63e5" ON "message_type_pid_dataset" ("message_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca5c06787d05e2c4aab60413d3" ON "message_type_pid_dataset" ("pid_dataset_id") `);
        await queryRunner.query(`CREATE TABLE "ecu_pid_dataset" ("pid_dataset_id" integer NOT NULL, "ecu_id" integer NOT NULL, CONSTRAINT "PK_4f8929e7e61e6fd35c775e6ee2d" PRIMARY KEY ("pid_dataset_id", "ecu_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9642825b253339f1dd096c5e25" ON "ecu_pid_dataset" ("pid_dataset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f26846ba382cf13481c0686c08" ON "ecu_pid_dataset" ("ecu_id") `);
        await queryRunner.query(`CREATE TABLE "dtc_dataset_dtc" ("dtc_id" integer NOT NULL, "dtc_dataset_id" integer NOT NULL, CONSTRAINT "PK_bcaa1c4b225df346255b8041fee" PRIMARY KEY ("dtc_id", "dtc_dataset_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a919dc6e656af4d2493f9d6ab4" ON "dtc_dataset_dtc" ("dtc_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_93d2d1e10637543ea299dfc5c1" ON "dtc_dataset_dtc" ("dtc_dataset_id") `);
        await queryRunner.query(`CREATE TABLE "ecu_dtc_dataset" ("dtc_dataset_id" integer NOT NULL, "ecu_id" integer NOT NULL, CONSTRAINT "PK_86f6579985d2853698aa727b65d" PRIMARY KEY ("dtc_dataset_id", "ecu_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc92530a3bb4ba6548f5ccbc87" ON "ecu_dtc_dataset" ("dtc_dataset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d19b1857794dac857a9e29b47d" ON "ecu_dtc_dataset" ("ecu_id") `);
        await queryRunner.query(`ALTER TABLE "dtc" DROP CONSTRAINT "UQ_b02ca9fc06592e35344cfa16009"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "severity"`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "description" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD CONSTRAINT "FK_9865d1714ff6f4e86d9ee030438" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "firmware_management" ADD CONSTRAINT "FK_4d2d120fe9ac6181239674b3ee1" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_1bf81b53a0a643f536e66755b62" FOREIGN KEY ("neg_id") REFERENCES "negative_response_codes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5" FOREIGN KEY ("parameter_id") REFERENCES "parameters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" ADD CONSTRAINT "FK_03da0196097403a22e19ac63e5f" FOREIGN KEY ("message_type_id") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" ADD CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_9642825b253339f1dd096c5e257" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_f26846ba382cf13481c0686c08c" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dtc_dataset_dtc" ADD CONSTRAINT "FK_a919dc6e656af4d2493f9d6ab4c" FOREIGN KEY ("dtc_id") REFERENCES "dtc"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dtc_dataset_dtc" ADD CONSTRAINT "FK_93d2d1e10637543ea299dfc5c16" FOREIGN KEY ("dtc_dataset_id") REFERENCES "dtc_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c" FOREIGN KEY ("dtc_dataset_id") REFERENCES "dtc_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_d19b1857794dac857a9e29b47d9" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle_ecu" ADD CONSTRAINT "FK_c1a17e66d1050ff898975645761" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle_ecu" DROP CONSTRAINT "FK_c1a17e66d1050ff898975645761"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_d19b1857794dac857a9e29b47d9"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c"`);
        await queryRunner.query(`ALTER TABLE "dtc_dataset_dtc" DROP CONSTRAINT "FK_93d2d1e10637543ea299dfc5c16"`);
        await queryRunner.query(`ALTER TABLE "dtc_dataset_dtc" DROP CONSTRAINT "FK_a919dc6e656af4d2493f9d6ab4c"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_f26846ba382cf13481c0686c08c"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_9642825b253339f1dd096c5e257"`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" DROP CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c"`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" DROP CONSTRAINT "FK_03da0196097403a22e19ac63e5f"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_1bf81b53a0a643f536e66755b62"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" DROP CONSTRAINT "FK_4d2d120fe9ac6181239674b3ee1"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP CONSTRAINT "FK_9865d1714ff6f4e86d9ee030438"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "dtc" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "severity" character varying`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dtc" ADD CONSTRAINT "UQ_b02ca9fc06592e35344cfa16009" UNIQUE ("code")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d19b1857794dac857a9e29b47d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc92530a3bb4ba6548f5ccbc87"`);
        await queryRunner.query(`DROP TABLE "ecu_dtc_dataset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93d2d1e10637543ea299dfc5c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a919dc6e656af4d2493f9d6ab4"`);
        await queryRunner.query(`DROP TABLE "dtc_dataset_dtc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f26846ba382cf13481c0686c08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9642825b253339f1dd096c5e25"`);
        await queryRunner.query(`DROP TABLE "ecu_pid_dataset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca5c06787d05e2c4aab60413d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03da0196097403a22e19ac63e5"`);
        await queryRunner.query(`DROP TABLE "message_type_pid_dataset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42e3cc1aecf0dd92ae884bb6e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9eff1d7cfde8b0520f7f386336"`);
        await queryRunner.query(`DROP TABLE "pid_dataset_pid"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3cc4d1b98879c5f935bbe5257"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bd37757d1cd557bcbf985dd3e"`);
        await queryRunner.query(`DROP TABLE "parameter_pid"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48c783f58fdae9de1ff18e4b84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bf81b53a0a643f536e66755b6"`);
        await queryRunner.query(`DROP TABLE "ecu_neg"`);
        await queryRunner.query(`DROP TABLE "ecu_attributes"`);
        await queryRunner.query(`DROP TABLE "firmware_management"`);
        await queryRunner.query(`DROP TABLE "ecu_management"`);
        await queryRunner.query(`DROP TABLE "dtc_dataset"`);
        await queryRunner.query(`DROP TABLE "pid_dataset"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "pid"`);
        await queryRunner.query(`DROP TABLE "parameters"`);
        await queryRunner.query(`DROP TABLE "negative_response_codes"`);
        await queryRunner.query(`ALTER TABLE "vehicle_ecu" ADD CONSTRAINT "FK_c1a17e66d1050ff898975645761" FOREIGN KEY ("ecu_id") REFERENCES "ecu"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
