import { MigrationInterface, QueryRunner } from "typeorm";

export class VheicleSegmentRels1733906706082 implements MigrationInterface {
    name = 'VheicleSegmentRels1733906706082'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_d2f5c06191aab95d4549fc8a803"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_6ca4c0fa9804dab09c8c7f3e93a"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_44998c737ae8ca1c75cae0f8431"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_431431bcdf697c3ae0dce460104"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_930540d66d3b8be7a733c1db0b3"`);
        await queryRunner.query(`ALTER TABLE "device" DROP CONSTRAINT "FK_4e45895a2aec400786bb56ed0a9"`);
        await queryRunner.query(`ALTER TABLE "service_ticket" DROP CONSTRAINT "FK_f55b83f763efe2c429c5987c47b"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" DROP CONSTRAINT "FK_4d2d120fe9ac6181239674b3ee1"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP CONSTRAINT "FK_9865d1714ff6f4e86d9ee030438"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_d19b1857794dac857a9e29b47d9"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_1bf81b53a0a643f536e66755b62"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_9642825b253339f1dd096c5e257"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_f26846ba382cf13481c0686c08c"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26"`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" DROP CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" RENAME COLUMN "vehicle_id" TO "firmware_type"`);
        await queryRunner.query(`CREATE TABLE "vehicle_segment" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_11f8ee3c02529fb393f665ca4e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_version" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "price" integer NOT NULL, "features" jsonb, CONSTRAINT "PK_dc6b011541904b9eda8abb6a825" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_owner" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone_number" character varying NOT NULL, "address" character varying NOT NULL, "purchase_date" TIMESTAMP NOT NULL, CONSTRAINT "PK_ac9360a2c16ec48e49e08e40d2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_parts_replacement" ("id" SERIAL NOT NULL, "part_name" character varying NOT NULL, "part_number" character varying NOT NULL, "replacement_date" TIMESTAMP NOT NULL, "cost" integer NOT NULL, "warranty_expiry" TIMESTAMP NOT NULL, "replaced_by" character varying NOT NULL, "vehicle_id" integer, CONSTRAINT "PK_6169159d005776aba565ac00097" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_insurance" ("id" SERIAL NOT NULL, "policy_number" character varying NOT NULL, "provider_name" character varying NOT NULL, "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP NOT NULL, "coverage_details" jsonb, "vehicle_id" integer, CONSTRAINT "PK_d97238c7cf1c63ee0ff6ab1b311" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dealer" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "location" character varying NOT NULL, "contact_information" jsonb, CONSTRAINT "PK_1bd6073e224f6c22ff1d5827add" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_sub_model_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_variant_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "oem_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "REL_930540d66d3b8be7a733c1db0b"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "service_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "dongle_conn_status"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "mac_address"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "imei"`);
        await queryRunner.query(`ALTER TABLE "service_ticket" DROP CONSTRAINT "UQ_f55b83f763efe2c429c5987c47b"`);
        await queryRunner.query(`ALTER TABLE "service_ticket" DROP COLUMN "vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP COLUMN "vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP COLUMN "dtc_dataset"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP COLUMN "pid_dataset"`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "country" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "founded_year" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "contact_information" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "website" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "launch_year" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "discontinued_year" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "oem_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "vehicle_version_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "vehicle_segment_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vin" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "UQ_960e864037056a9e38cb4277bdd" UNIQUE ("vin")`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "engine_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "UQ_1610f0d6f95af679546007ffee1" UNIQUE ("engine_number")`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "color" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "manufacture_year" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "transmission_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "mileage" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_sub_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_segment_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_version_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_owner_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "dealer_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "engine_capacity" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "fuel_efficiency" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "vehicleModelId" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "vehicle_version_id" integer`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "dongle_serial_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD CONSTRAINT "UQ_86049bc8c7915ec7f8e16f4134a" UNIQUE ("dongle_serial_number")`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "model" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "manufacture_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "firmware_version" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."dongle_status_enum" AS ENUM('Available', 'Assigned', 'Defective')`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "status" "public"."dongle_status_enum" NOT NULL DEFAULT 'Available'`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "firmware_updated_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "assigned_device_id" integer`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD CONSTRAINT "UQ_bb3b45dcc3bd8ad9b400991badd" UNIQUE ("assigned_device_id")`);
        await queryRunner.query(`ALTER TABLE "device" ADD "device_name" character varying`);
        await queryRunner.query(`ALTER TABLE "device" ADD "device_type" character varying`);
        await queryRunner.query(`ALTER TABLE "device" ADD "os_version" character varying`);
        await queryRunner.query(`ALTER TABLE "device" ADD "serial_number" character varying`);
        await queryRunner.query(`ALTER TABLE "device" ADD CONSTRAINT "UQ_c7f756679d925ed3d51af6cb8f2" UNIQUE ("serial_number")`);
        await queryRunner.query(`ALTER TABLE "device" ADD "registration_date" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."device_status_enum" AS ENUM('Active', 'Inactive', 'Suspended')`);
        await queryRunner.query(`ALTER TABLE "device" ADD "status" "public"."device_status_enum" NOT NULL DEFAULT 'Active'`);
        await queryRunner.query(`ALTER TABLE "device" ADD "created_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "device" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "device" ADD "assigned_to" integer`);
        await queryRunner.query(`ALTER TABLE "device" ADD CONSTRAINT "UQ_c0ab4ca240cd2b5148d0b1868e9" UNIQUE ("assigned_to")`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD "firmware_id" integer`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "firmware_management" DROP COLUMN "firmware_type"`);
        await queryRunner.query(`CREATE TYPE "public"."firmware_management_firmware_type_enum" AS ENUM('DEVOTA', 'DOTA')`);
        await queryRunner.query(`ALTER TABLE "firmware_management" ADD "firmware_type" "public"."firmware_management_firmware_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD CONSTRAINT "FK_7e1f018275fd8db5308687986b8" FOREIGN KEY ("oem_id") REFERENCES "oem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD CONSTRAINT "FK_be9e7dc42d899d3dbfbea514ff4" FOREIGN KEY ("vehicle_version_id") REFERENCES "vehicle_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD CONSTRAINT "FK_bed31a4916e39fc2f1d132642dc" FOREIGN KEY ("vehicle_segment_id") REFERENCES "vehicle_segment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_parts_replacement" ADD CONSTRAINT "FK_f8d51b8046f1b7117684f11f326" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_insurance" ADD CONSTRAINT "FK_683160da182ea8fce3238a0459d" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_d2f5c06191aab95d4549fc8a803" FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_2c4475836273750ab1156df6e46" FOREIGN KEY ("vehicle_sub_id") REFERENCES "vehicle_sub_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_8fb5c23b8b5d8f596ac72ffd1c1" FOREIGN KEY ("vehicle_segment_id") REFERENCES "vehicle_segment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_f03e0bda7a4744ff9edff67c710" FOREIGN KEY ("vehicle_version_id") REFERENCES "vehicle_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_8d0a971f2191e51336e203c748e" FOREIGN KEY ("vehicle_owner_id") REFERENCES "vehicle_owner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_9665b30d49f838e2eff43f9abe0" FOREIGN KEY ("dealer_id") REFERENCES "dealer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD CONSTRAINT "FK_4c8eefa4b7986302de991313a62" FOREIGN KEY ("vehicleModelId") REFERENCES "vehicle_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD CONSTRAINT "FK_1be98aa26a907334f4d63d6b4bf" FOREIGN KEY ("vehicle_version_id") REFERENCES "vehicle_version"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD CONSTRAINT "FK_bb3b45dcc3bd8ad9b400991badd" FOREIGN KEY ("assigned_device_id") REFERENCES "device"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device" ADD CONSTRAINT "FK_4e45895a2aec400786bb56ed0a9" FOREIGN KEY ("dongle_id") REFERENCES "dongle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device" ADD CONSTRAINT "FK_c0ab4ca240cd2b5148d0b1868e9" FOREIGN KEY ("assigned_to") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD CONSTRAINT "FK_53b183abdc665d3ffb74833bdb1" FOREIGN KEY ("firmware_id") REFERENCES "firmware_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5" FOREIGN KEY ("parameter_id") REFERENCES "parameters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c" FOREIGN KEY ("dtc_dataset_id") REFERENCES "dtc_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_d19b1857794dac857a9e29b47d9" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_1bf81b53a0a643f536e66755b62" FOREIGN KEY ("neg_id") REFERENCES "negative_response_codes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_f26846ba382cf13481c0686c08c" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_9642825b253339f1dd096c5e257" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" ADD CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" DROP CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_9642825b253339f1dd096c5e257"`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" DROP CONSTRAINT "FK_f26846ba382cf13481c0686c08c"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a"`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" DROP CONSTRAINT "FK_1bf81b53a0a643f536e66755b62"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_d19b1857794dac857a9e29b47d9"`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" DROP CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26"`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" DROP CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576"`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" DROP CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP CONSTRAINT "FK_53b183abdc665d3ffb74833bdb1"`);
        await queryRunner.query(`ALTER TABLE "device" DROP CONSTRAINT "FK_c0ab4ca240cd2b5148d0b1868e9"`);
        await queryRunner.query(`ALTER TABLE "device" DROP CONSTRAINT "FK_4e45895a2aec400786bb56ed0a9"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP CONSTRAINT "FK_bb3b45dcc3bd8ad9b400991badd"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP CONSTRAINT "FK_1be98aa26a907334f4d63d6b4bf"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP CONSTRAINT "FK_4c8eefa4b7986302de991313a62"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_9665b30d49f838e2eff43f9abe0"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_8d0a971f2191e51336e203c748e"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_f03e0bda7a4744ff9edff67c710"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_8fb5c23b8b5d8f596ac72ffd1c1"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_2c4475836273750ab1156df6e46"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_d2f5c06191aab95d4549fc8a803"`);
        await queryRunner.query(`ALTER TABLE "vehicle_insurance" DROP CONSTRAINT "FK_683160da182ea8fce3238a0459d"`);
        await queryRunner.query(`ALTER TABLE "vehicle_parts_replacement" DROP CONSTRAINT "FK_f8d51b8046f1b7117684f11f326"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP CONSTRAINT "FK_bed31a4916e39fc2f1d132642dc"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP CONSTRAINT "FK_be9e7dc42d899d3dbfbea514ff4"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP CONSTRAINT "FK_7e1f018275fd8db5308687986b8"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" DROP COLUMN "firmware_type"`);
        await queryRunner.query(`DROP TYPE "public"."firmware_management_firmware_type_enum"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" ADD "firmware_type" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" ADD "name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" ADD "name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "oem" ADD "name" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ecu_management" DROP COLUMN "firmware_id"`);
        await queryRunner.query(`ALTER TABLE "device" DROP CONSTRAINT "UQ_c0ab4ca240cd2b5148d0b1868e9"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "assigned_to"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."device_status_enum"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "registration_date"`);
        await queryRunner.query(`ALTER TABLE "device" DROP CONSTRAINT "UQ_c7f756679d925ed3d51af6cb8f2"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "serial_number"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "os_version"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "device_type"`);
        await queryRunner.query(`ALTER TABLE "device" DROP COLUMN "device_name"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP CONSTRAINT "UQ_bb3b45dcc3bd8ad9b400991badd"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "assigned_device_id"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "firmware_updated_at"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."dongle_status_enum"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "firmware_version"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "manufacture_date"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "model"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP CONSTRAINT "UQ_86049bc8c7915ec7f8e16f4134a"`);
        await queryRunner.query(`ALTER TABLE "dongle" DROP COLUMN "dongle_serial_number"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "vehicle_version_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "vehicleModelId"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "fuel_efficiency"`);
        await queryRunner.query(`ALTER TABLE "vehicle_sub_model" DROP COLUMN "engine_capacity"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "dealer_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_owner_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_version_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_segment_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_sub_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "mileage"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "transmission_type"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "manufacture_year"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "UQ_1610f0d6f95af679546007ffee1"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "engine_number"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "UQ_960e864037056a9e38cb4277bdd"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "vin"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "vehicle_segment_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "vehicle_version_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "oem_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "discontinued_year"`);
        await queryRunner.query(`ALTER TABLE "vehicle_model" DROP COLUMN "launch_year"`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "contact_information"`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "founded_year"`);
        await queryRunner.query(`ALTER TABLE "oem" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD "pid_dataset" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD "dtc_dataset" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD "vehicle_id" integer`);
        await queryRunner.query(`ALTER TABLE "service_ticket" ADD "vehicle_id" integer`);
        await queryRunner.query(`ALTER TABLE "service_ticket" ADD CONSTRAINT "UQ_f55b83f763efe2c429c5987c47b" UNIQUE ("vehicle_id")`);
        await queryRunner.query(`ALTER TABLE "device" ADD "imei" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "device" ADD "mac_address" character varying(17)`);
        await queryRunner.query(`ALTER TABLE "device" ADD "name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device" ADD "dongle_conn_status" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "dongle" ADD "name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "name" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "service_ticket_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "REL_930540d66d3b8be7a733c1db0b" UNIQUE ("service_ticket_id")`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "oem_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_variant_id" integer`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "vehicle_sub_model_id" integer`);
        await queryRunner.query(`DROP TABLE "dealer"`);
        await queryRunner.query(`DROP TABLE "vehicle_insurance"`);
        await queryRunner.query(`DROP TABLE "vehicle_parts_replacement"`);
        await queryRunner.query(`DROP TABLE "vehicle_owner"`);
        await queryRunner.query(`DROP TABLE "vehicle_version"`);
        await queryRunner.query(`DROP TABLE "vehicle_segment"`);
        await queryRunner.query(`ALTER TABLE "firmware_management" RENAME COLUMN "firmware_type" TO "vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "message_type_pid_dataset" ADD CONSTRAINT "FK_ca5c06787d05e2c4aab60413d3c" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_42e3cc1aecf0dd92ae884bb6e26" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pid_dataset_pid" ADD CONSTRAINT "FK_9eff1d7cfde8b0520f7f3863365" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_bc92530a3bb4ba6548f5ccbc87c" FOREIGN KEY ("dtc_dataset_id") REFERENCES "dtc_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_f26846ba382cf13481c0686c08c" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_pid_dataset" ADD CONSTRAINT "FK_9642825b253339f1dd096c5e257" FOREIGN KEY ("pid_dataset_id") REFERENCES "pid_dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_48c783f58fdae9de1ff18e4b84a" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ecu_neg" ADD CONSTRAINT "FK_1bf81b53a0a643f536e66755b62" FOREIGN KEY ("neg_id") REFERENCES "negative_response_codes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_dtc_dataset" ADD CONSTRAINT "FK_d19b1857794dac857a9e29b47d9" FOREIGN KEY ("ecu_id") REFERENCES "ecu_management"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_f3cc4d1b98879c5f935bbe52576" FOREIGN KEY ("pid_id") REFERENCES "pid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parameter_pid" ADD CONSTRAINT "FK_6bd37757d1cd557bcbf985dd3e5" FOREIGN KEY ("parameter_id") REFERENCES "parameters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ecu_management" ADD CONSTRAINT "FK_9865d1714ff6f4e86d9ee030438" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "firmware_management" ADD CONSTRAINT "FK_4d2d120fe9ac6181239674b3ee1" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_ticket" ADD CONSTRAINT "FK_f55b83f763efe2c429c5987c47b" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "device" ADD CONSTRAINT "FK_4e45895a2aec400786bb56ed0a9" FOREIGN KEY ("dongle_id") REFERENCES "dongle"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_930540d66d3b8be7a733c1db0b3" FOREIGN KEY ("service_ticket_id") REFERENCES "service_ticket"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_431431bcdf697c3ae0dce460104" FOREIGN KEY ("oem_id") REFERENCES "oem"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_44998c737ae8ca1c75cae0f8431" FOREIGN KEY ("vehicle_variant_id") REFERENCES "vehicle_variant"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_6ca4c0fa9804dab09c8c7f3e93a" FOREIGN KEY ("vehicle_sub_model_id") REFERENCES "vehicle_sub_model"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_d2f5c06191aab95d4549fc8a803" FOREIGN KEY ("vehicle_model_id") REFERENCES "vehicle_model"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
